name: Legacy tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]
        plone: ["52"]
    steps:
      - uses: actions/checkout@v4
      - name: Cache eggs
        uses: actions/cache@v4
        with:
          path: eggs
          key: ${{ runner.OS }}-build-python${{ matrix.python }}-${{ matrix.plone }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -c constraints_plone${{ matrix.plone }}.txt
          cp test_plone${{ matrix.plone }}.cfg buildout.cfg
      - name: Install buildout
        run: |
          buildout -N -t 3 code-analysis:return-status-codes=True
      - name: Run tests
        run: |
            bin/test